ALTER TABLE properties ADD COLUMN IF NOT EXISTS image TEXT;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS rating DECIMAL(2, 1);
ALTER TABLE properties ADD COLUMN IF NOT EXISTS tags TEXT[];
ALTER TABLE properties ADD COLUMN IF NOT EXISTS details JSONB;
ALTER TABLE properties ADD COLUMN IF NOT EXISTS gallery TEXT[];
